### ISSUE TITLE
How do i calculate the end time of a slider?

### ISSUE THREAD

**Issue by AlexCatDev** [Razacx/osuBMParser#2]
Title ^^ please tell me

**Comment by N3bby** [comment]
I did some research about a year ago, but idk if this information is correct.

var pixelsPerBeat = beatmap.SliderMultiplier * currentTimingPoint.MsPerBeat;
var sliderLengthInBeats = (slider.PixelLength * slider.Repeat) / pixelsPerBeat;
var sliderLengthInMs = pixelsPerBeat * sliderLengthInBeats;

Best thing you can do is experiment a bit. My original source for this was somewhere on the official osu! forums, but I can't find the link anymore :/

Hope this helps!

Edit: Also, little heads up. The specification here  https://osu.ppy.sh/help/wiki/osu!_File_Formats/Osu_(file_format)
states that the MsPerBeat property for timing points can be negative. In that case, the following applies:

"An inherited Timing Point differs from a Timing point in that the Milliseconds per Beat value is negative, and defines a new Milliseconds per Beat based on the last non-inherited Timing Point. This can be used to change volume without affecting offset timing, or changing slider speeds."

So you might want to process the timingpoints when they get parsed, since my library is currently not handling this (I think?).
